language: ruby
services:
  - cassandra

matrix:
  include:
    - sudo: required
      dist: trusty

    - sudo: required
      dist: precise

    - sudo: false
      dist: trusty

    - sudo: false
      dist: precise
      

script: mysql -V; cassandra -v
