matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: precise
      sudo: required

language: generic

script: export MGD=`mongod --version`
