os: linux
dist: trusty
language: ruby

addons:
  postgresql: "9.6"

apt:
  packages:
    - postgresql-9.6-postgis-2.3

services:
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis"
