matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: ruby
    - os: linux
      dist: trusty
      sudo: false
      language: ruby
    - os: linux
      dist: precise
      sudo: required
      language: ruby
    - os: osx
      dist: precise
      sudo: required
      language: ruby
script: df -h
