install: true
script: true
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
    - os: linux
      dist: trusty
      sudo: false
      language: python
