matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: precise
      sudo: required
    - os: osx

script: mongod --version
